# Configuration des services avec injection de dépendances
# Structure: service_id -> classe

# Services Core
database: App\Core\Database
session: App\Core\Session
validator: App\Core\Validator
router: App\Core\Router
fileUpload: App\Core\FileUpload
lang: App\Core\Lang
middleware: App\Core\MiddlewareLoader
reflectionFactory: App\Core\ReflectionFactory

# Repositories
userRepo: Src\Repository\UserRepository
compteRepo: Src\Repository\CompteRepository
transactionRepo: Src\Repository\TransactionRepository

# Services métier
securityServ: Src\Service\SecurityService
compteServ: Src\Service\CompteService
transactionServ: Src\Service\TransactionService
appdafServ: Src\Service\AppDAFService
woyofalServ: Src\Service\WoyofalService

# Contrôleurs
compteController: Src\Controller\CompteController
securityController: Src\Controller\SecurityController
woyofalController: Src\Controller\WoyofalController
